# k8s/data-collector-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-collector
  namespace: ai-noc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: data-collector
  template:
    metadata:
      labels:
        app: data-collector
    spec:
      containers:
      - name: data-collector
        image: ai-noc/data-collector:latest
        ports:
        - containerPort: 8080
        env:
        - name: SNMP_COMMUNITY
          valueFrom:
            secretKeyRef:
              name: snmp-secret
              key: community
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: data-collector-service
  namespace: ai-noc
spec:
  selector:
    app: data-collector
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP
