apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    access: proxy
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 15s
      queryTimeout: 60s
      httpMethod: POST
      
  - name: InfluxDB
    type: influxdb
    url: http://influxdb:8086
    access: proxy
    database: network-metrics
    user: admin
    password: adminpassword
    jsonData:
      version: Flux
      organization: ai-noc
      defaultBucket: network-metrics
      tlsSkipVerify: true
    secureJsonData:
      token: admin-token-12345
